name: Notify Slack on Push Request

on:
  push:
    branches:
      - main

jobs:
  notifySlack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack message on PR open/reopen
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_PR_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          PR_TITLE: ${{ github.event.push_request.title }}
          PR_URL: ${{ github.event.push_request.html_url }}
          PR_USER: ${{ github.event.push_request.user.login }}
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-type: application/json" \
            --data '{
              "channel": "'"$SLACK_PR_CHANNEL_ID"'",
              "text": ":bell: Push Request *'"$SlackNotify"'* opened by *'"$mayank-9557"'*\n<'"$PR_URL"'|View Push Request>"
            }'